package com.bi.exchange.model;

import com.bi.exchange.framework.model.Column;
import com.bi.exchange.framework.model.Table;

/**
 * auto generated by generation tools v1.0.0
 */
@Table(scheme = "match_config")
public class MatchConfig {

    private String currencyPair;
    private String zeromqUrlport;
    private String zeromqRevokeurlport;
    private String zeromqMarketurlport;


    @Column(name = "CURRENCY_PAIR")
    public String getCurrencyPair() {
        return currencyPair;
    }

    public void setCurrencyPair(String currencyPair) {
        this.currencyPair = currencyPair;
    }

    @Column(name = "ZEROMQ_URLPORT")
    public String getZeromqUrlport() {
        return zeromqUrlport;
    }

    public void setZeromqUrlport(String zeromqUrlport) {
        this.zeromqUrlport = zeromqUrlport;
    }

    @Column(name = "ZEROMQ_REVOKEURLPORT")
    public String getZeromqRevokeurlport() {
        return zeromqRevokeurlport;
    }

    public void setZeromqRevokeurlport(String zeromqRevokeurlport) {
        this.zeromqRevokeurlport = zeromqRevokeurlport;
    }

    @Column(name = "ZEROMQ_MARKETPORT")
    public String getZeromqMarketurlport() {
        return zeromqMarketurlport;
    }

    public void setZeromqMarketurlport(String zeromqMarketurlport) {
        this.zeromqMarketurlport = zeromqMarketurlport;
    }
}
